2023-10-08 12:33:29,366 - Rotating Log - ERROR - bitmap "C:\Users\jason\PycharmProjects\deltadeltactpersonal\umbi-square.ico" not defined
2023-10-08 12:33:29,366 - Rotating Log - ERROR - bitmap "C:\Users\jason\PycharmProjects\deltadeltactpersonal\umbi-square.ico" not defined
2023-10-08 12:33:29,394 - Rotating Log - ERROR - Traceback (most recent call last):
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 44, in __init__
    self.iconbitmap(os.path.join(basedir, 'umbi-square.ico'))
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "C:\Users\jason\PycharmProjects\deltadeltactpersonal\umbi-square.ico" not defined

2023-10-08 12:33:29,394 - Rotating Log - ERROR - Traceback (most recent call last):
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 44, in __init__
    self.iconbitmap(os.path.join(basedir, 'umbi-square.ico'))
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "C:\Users\jason\PycharmProjects\deltadeltactpersonal\umbi-square.ico" not defined

2023-10-08 12:33:30,880 - Rotating Log - ERROR - bitmap "C:\Users\jason\PycharmProjects\deltadeltactpersonal\umbi-square.ico" not defined
2023-10-08 12:33:30,880 - Rotating Log - ERROR - bitmap "C:\Users\jason\PycharmProjects\deltadeltactpersonal\umbi-square.ico" not defined
2023-10-08 12:33:30,881 - Rotating Log - ERROR - Traceback (most recent call last):
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 998, in run_app
    app = App()
          ^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 44, in __init__
    self.iconbitmap(os.path.join(basedir, 'umbi-square.ico'))
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "C:\Users\jason\PycharmProjects\deltadeltactpersonal\umbi-square.ico" not defined

2023-10-08 12:33:30,881 - Rotating Log - ERROR - Traceback (most recent call last):
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 998, in run_app
    app = App()
          ^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 44, in __init__
    self.iconbitmap(os.path.join(basedir, 'umbi-square.ico'))
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "C:\Users\jason\PycharmProjects\deltadeltactpersonal\umbi-square.ico" not defined

2024-02-04 16:51:23,741 - Rotating Log - ERROR - bad option "-bg": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
2024-02-04 16:51:23,741 - Rotating Log - ERROR - bad option "-bg": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
2024-02-04 16:51:23,752 - Rotating Log - ERROR - Traceback (most recent call last):
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 67, in __init__
    self.canvas.grid(row=0, column=0, sticky="nsew", bg="blue")
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2549, in grid_configure
    self.tk.call(
_tkinter.TclError: bad option "-bg": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky

2024-02-04 16:51:23,752 - Rotating Log - ERROR - Traceback (most recent call last):
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 67, in __init__
    self.canvas.grid(row=0, column=0, sticky="nsew", bg="blue")
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2549, in grid_configure
    self.tk.call(
_tkinter.TclError: bad option "-bg": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky

2024-02-04 16:51:25,150 - Rotating Log - ERROR - bad option "-bg": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
2024-02-04 16:51:25,150 - Rotating Log - ERROR - bad option "-bg": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
2024-02-04 16:51:25,151 - Rotating Log - ERROR - Traceback (most recent call last):
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 1044, in run_app
    app = App()
          ^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 67, in __init__
    self.canvas.grid(row=0, column=0, sticky="nsew", bg="blue")
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2549, in grid_configure
    self.tk.call(
_tkinter.TclError: bad option "-bg": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky

2024-02-04 16:51:25,151 - Rotating Log - ERROR - Traceback (most recent call last):
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 1044, in run_app
    app = App()
          ^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 67, in __init__
    self.canvas.grid(row=0, column=0, sticky="nsew", bg="blue")
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2549, in grid_configure
    self.tk.call(
_tkinter.TclError: bad option "-bg": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky

2024-02-04 16:52:02,499 - Rotating Log - ERROR - cannot use geometry manager grid inside .!frame which already has slaves managed by pack
2024-02-04 16:52:02,499 - Rotating Log - ERROR - cannot use geometry manager grid inside .!frame which already has slaves managed by pack
2024-02-04 16:52:02,501 - Rotating Log - ERROR - Traceback (most recent call last):
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 71, in __init__
    vertical_scrollbar.grid(row=0, column=1, sticky='ns')
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2549, in grid_configure
    self.tk.call(
_tkinter.TclError: cannot use geometry manager grid inside .!frame which already has slaves managed by pack

2024-02-04 16:52:02,501 - Rotating Log - ERROR - Traceback (most recent call last):
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\logger.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\PycharmProjects\deltadeltactpersonal\interface.py", line 71, in __init__
    vertical_scrollbar.grid(row=0, column=1, sticky='ns')
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2549, in grid_configure
    self.tk.call(
_tkinter.TclError: cannot use geometry manager grid inside .!frame which already has slaves managed by pack

2024-02-04 16:52:04,000 - Rotating Log - ERROR - cannot use geometry manager grid inside .!frame which already has slaves managed by pack
2024-02-04 16:52:04,000 - Rotating Log - ERROR - cannot use geometry manager grid inside .!frame which already has slaves managed by pack
